#!/usr/bin/env node
/*
 * test-nudge.js
 *
 * PostToolUse hook (Edit | Write). When Claude edits a Swift source or test
 * file, inject a system-reminder to run the test suite (and, for
 * user-visible changes, build and launch the app) before declaring the
 * task complete. Evidence before claims.
 *
 * Also reminds about the project.yml ↔ .xcodeproj sync when project.yml
 * is edited, since the Xcode project is generated by XcodeGen but committed.
 *
 * Failure mode: any error → exit 0 (the hook never breaks Claude) plus a
 * one-line stderr log so failures surface in `claude --debug` output.
 */

'use strict'

function logErr(where, err) {
  try {
    const msg = err && (err.stack || err.message || String(err))
    process.stderr.write(`[test-nudge] ${where}: ${msg}\n`)
  } catch { /* never throw from the logger */ }
}

const TEST_CMD =
  'cd claude-usage-systray && xcodebuild test -project ClaudeUsageSystray.xcodeproj ' +
  "-scheme ClaudeUsageSystrayTests -destination 'platform=macOS' " +
  'CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO'

function buildReminder(filePath) {
  const lower = filePath.toLowerCase()

  if (lower.endsWith('project.yml')) {
    return (
      '⚠️ project.yml edited. The .xcodeproj is generated from it but committed — ' +
      'run `xcodegen generate` inside claude-usage-systray/ and commit both files.'
    )
  }

  if (!lower.endsWith('.swift')) return null
  if (!lower.includes('/sources/') && !lower.includes('/tests/')) return null

  return (
    `⚠️ Swift file edited: ${filePath}\n` +
    'Before declaring this task complete:\n' +
    `   1. Run the test suite: ${TEST_CMD}\n` +
    '   2. If the change is user-visible (menu bar text, popover, notifications), build and run the app to confirm the behavior.\n' +
    '   3. Report the actual pass/fail output — no "should work" claims.'
  )
}

function main() {
  let input = ''
  process.stdin.on('data', (chunk) => { input += chunk })
  process.stdin.on('end', () => {
    try {
      const payload = JSON.parse(input || '{}')
      const filePath = payload.tool_input && payload.tool_input.file_path
      if (!filePath) return process.exit(0)

      const reminder = buildReminder(String(filePath))
      if (!reminder) return process.exit(0)

      process.stdout.write(JSON.stringify({
        hookSpecificOutput: {
          hookEventName: 'PostToolUse',
          additionalContext: reminder,
        },
      }))
      process.exit(0)
    } catch (err) {
      logErr('main', err)
      process.exit(0)
    }
  })
}

main()
